# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9VyXr-AFKXc3Fya8RZLiaBU2XGdKrxI

🔹 Etapa 1 – Imports
"""

import pandas as pd
from data_clean import DataClean
from transform import tempo_voo_horas_para_minutos, classifica_turno_partida
from utils import create_db
from sqlalchemy import create_engine

"""🔹 Etapa 2 – Carregar dados"""

url = "https://raw.githubusercontent.com/JackyP/testing/master/datasets/nycflights.csv"
df = pd.read_csv(url)
df.head()

"""🔹 Etapa 3 – Criar config de colunas"""

config_dict = {
    "id": [0, 1, 2, 3, 4, 5, 6, 7],
    "nome_original": ["dep_time", "arr_delay", "carrier", "flight", "air_time", "distance", "origin", "dest"],
    "nome": ["data_hora", "atraso_chegada", "companhia", "id_voo", "tempo_voo", "distancia", "origem", "destino"],
    "aceita_negativo": [0, 1, 1, 1, 1, 1, 1, 1],
    "tipo": ["date", "float", "str", "str", "float", "float", "str", "str"]
}
config_df = pd.DataFrame(config_dict)

print(df.columns.tolist())

"""🔹 Etapa 4 – Aplicar limpeza com DataClean"""

limpador = DataClean(df, config_df)
limpador.select_cols()
limpador.rename_cols()
limpador.select_nnull_cols()
limpador.select_nneg_cols()

df_limpo = limpador.return_data()
df_limpo.head()

"""🔹 Etapa 5 – Aplicar transformações"""

df_transformado = tempo_voo_horas_para_minutos(df_limpo)
df_transformado = classifica_turno_partida(df_transformado)

df_transformado[['tempo_voo', 'tempo_voo_minutos', 'data_hora', 'turno_partida']].head()

"""🔹 Etapa 6 – Criar banco e salvar dados"""

engine = create_engine('sqlite:///voos01.db')
create_db(engine)
df_transformado.to_sql('flights', con=engine, if_exists='replace', index=False)

print("Dados transformados e salvos com sucesso.")